#!/usr/bin/env bash
# Every file path referenced by the docs must actually exist.
#
# The reference repo's skill cards cite `scripts/run-gatekeeper.sh`,
# `scripts/hydrate-dashboard.ts`, `ci-build.yml` and `pr-reviewer.yml` -- none of
# which were ever created. Documentation that lies is worse than none, because
# it is trusted. This makes the claim checkable.
set -euo pipefail

fail=0
checked=0

# Backticked paths that look like repo paths, plus markdown link targets.
scan() {
  local f="$1" dir; dir=$(dirname "$f")
  # Backticked strings containing a slash are PATHS. A bare filename in prose
  # ("build.yml's paths filter") is not a path claim, and a runtime artifact
  # like build-matrix.json does not exist in the tree. Requiring a slash keeps
  # the check meaningful while still catching the reference repo's failure mode
  # -- it cited `scripts/run-gatekeeper.sh`, which never existed.
  # `|| true` on every grep: a file with no matches makes grep exit 1, and
  # under `set -e` with `pipefail` that kills this whole subshell, silently
  # truncating the path list. The lint then passes having checked almost
  # nothing -- which is exactly how it first shipped.
  { grep -oE '`[A-Za-z0-9_.-]+(/[A-Za-z0-9_.-]+)+`' "$f" 2>/dev/null || true; } \
    | tr -d '`' | while read -r p; do echo "$dir|$p"; done
  # [text](path)  -- skip URLs and anchors
  { grep -oE '\]\([^)#]+\)' "$f" 2>/dev/null || true; } | sed 's/^](//; s/)$//' \
    | { grep -vE '^https?:' || true; } | while read -r p; do echo "$dir|$p"; done
}

# Paths generated by the setup runbook rather than committed. Referencing them
# is correct; they simply do not exist until SETUP-ENVIRONMENTS.md has been run.
setup_generated() {
  case "$1" in
    .github/pdp/public-keys/build.pub|.github/pdp/public-keys/review.pub|.github/pdp/public-keys/release.pub) return 0 ;;
    *) return 1 ;;
  esac
}

# A slash alone does not make something a path: `infrashift/trusted-base-images`
# is a GitHub org, `sonatype/nexus3` an image, `review/cve-policy` a status
# context, `os/user` a Go package. Only strings rooted in a real top-level
# directory of THIS repo are path claims worth checking.
repo_path() {
  case "$1" in
    scripts/*|.github/*|docs/*|.ai/*|Containerfiles/*|schemas/*|rootfs/*|../*|./*) return 0 ;;
    *) return 1 ;;
  esac
}

while IFS='|' read -r dir p; do
  [[ -z "$p" ]] && continue
  repo_path "$p" || continue
  setup_generated "$p" && { checked=$((checked + 1)); continue; }
  # Resolve relative to the referencing file, then fall back to repo root.
  if [[ -e "${dir}/${p}" || -e "$p" ]]; then
    checked=$((checked + 1))
  else
    echo "error: $(basename "$dir")/$(basename "$p"): referenced path does not exist -> ${p}" >&2
    fail=1
  fi
done < <(
  for f in CLAUDE.md README.md SETUP-ENVIRONMENTS.md .ai/PRD.md .ai/skills/*.md docs/**/*.md; do
    [[ -f "$f" ]] && scan "$f"
  done
)

if [[ "$fail" -eq 0 ]]; then
  echo "OK: ${checked} documented path(s) resolve"
fi
exit "$fail"
